
export const ActionTypes = {
  MAKE_TRANSFER: 'MAKE_TRANSFER',
  WITHDRAW_MONEY: 'WITHDRAW_MONEY',
  PUT_MONEY: 'PUT_MONEY',
  FAILED_TRANSACTION: 'FAILED_TRANSACTION',
  SET_ACTIVE_USER_INFO: 'SET_ACTIVE_USER_INFO'
};
