export const ActionTypes = {
  SET_SOURCE_CURRENCY: 'SET_SOURCE_CURRENCY',
  SET_TARGET_CURRENCY: 'SET_TARGET_CURRENCY',
  SET_REQUEST_AMOUNT: 'SET_REQUEST_AMOUNT',
  SET_EXCHANGE_RATE: 'SET_EXCHANGE_RATE',
  SET_CURRENCIES: 'SET_CURRENCIES'
};
