export const ActionTypes = {
  SET_SOURCE_CURRENCY: 'SET_SOURCE_CURRENCY',
  SET_TARGET_CURRENCY: 'SET_TARGET_CURRENCY',
  SET_REQUEST_AMOUNT: 'SET_REQUEST_AMOUNT',
  SET_TARGET_AMOUNT: 'SET_TARGET_AMOUNT',
  SET_CURRENCIES: 'SET_CURRENCIES',
  SWAP_CURRENCIES: 'SWAP_CURRENCIES',
  SET_EXCHANGE_RATE_POLLER_ID: 'SET_EXCHANGE_RATE_POLLER_ID',
  UPDATE_EXCHANGE_RATES: 'UPDATE_EXCHANGE_RATES'
};
